version: '3.1'
services:
  db:
    image: mysql
    container_name: mysql-api-anime
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - api_anime_data:/var/lib/mysql

volumes:
  api_anime_data: